language: ruby
rvm:
  - "2.0.0"
  - "2.1.3"
  - "2.2.0"
before_install:
  - wget -P ~ http://mafft.cbrc.jp/alignment/software/mafft-7.205-with-extensions-src.tgz
  - tar -zxvf ~/mafft-7.205-with-extensions-src.tgz -C ~
  - mkdir ~/mafft
  - ruby -pi -e "gsub(/^PREFIX = \/usr\/local/, 'PREFIX = ~/mafft/')" ~/mafft-7.205-with-extensions/core/Makefile
  - (cd ~/mafft-7.205-with-extensions/core/ && make clean && make && make install)
  - export PATH=$PATH:~/mafft/bin
cache: bundler
sudo: false 
script: bundle exec rake test
after_script: bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 2177997ae2dd26804c32e1ec34a2221f94b71a2170f6c1db2c020f8858cd87f2
